add sha256sum check for `install_clash_meta_metafile`

diff --git a/scripts/install_clash_meta_metafile b/scripts/install_clash_meta_metafile
--- a/scripts/install_clash_meta_metafile
+++ b/scripts/install_clash_meta_metafile
@@ -1,16 +1,22 @@
 #!/usr/bin/env bash
 
+set -e
+
 # https://zhuanlan.zhihu.com/p/678860499
 
 # https://sites.ipaddress.com/github.com/
 # https://sites.ipaddress.com/github.global.ssl.fastly.net/
 # https://sites.ipaddress.com/assets-cdn.github.com/
 
+RESET="\e[0m"
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+YELLOW="\e[1;33m"
+CYAN="\e[36m"
+
 GITHUB_MIRROR="https://hub.gitmirror.com/"
 
-GeoIP_metadb="${GITHUB_MIRROR}https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
-GeoIP_dat="${GITHUB_MIRROR}https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
-GeoSite_dat="${GITHUB_MIRROR}https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
+GR_URL="${GITHUB_MIRROR}https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/"
 
 TARGET_DIR="$HOME/.config/mihomo/"
 
@@ -33,19 +39,40 @@ all() {
   geosite_dat
 }
 
+dd() {
+  TARGET_NAME=$1
+  SRC_NAME=$2
+  FILE_P="$TARGET_DIR""$TARGET_NAME"
+  rm -rf "$FILE_P"
+  F_URL="$GR_URL""$SRC_NAME"
+  SHA_URL="$GR_URL""$SRC_NAME"".sha256sum"
+  TEMP_SHA_FILE=$(mktemp /tmp/clash_meta_metafile_"$SRC_NAME".XXXXXXXXXX)
+  wget --quiet --show-progress --continue "$F_URL" -O "$FILE_P"
+  wget --quiet --show-progress --continue "$SHA_URL" -O "$TEMP_SHA_FILE"
+  if echo "$(cat $TEMP_SHA_FILE | cut -d' ' -f1) $FILE_P" | sha256sum --check --status; then
+    rm -rf $TEMP_SHA_FILE
+    echo -e "${GREEN}INFO${RESET}: ${YELLOW}${FILE_P}${RESET} downloading finished!!!"
+  else
+    echo -e "${RED}ERROR${RESET}: ${CYAN}${FILE_P}${RESET} sha256sum check failed, the sha256sum file is located at ${CYAN}${TEMP_SHA_FILE}${RESET}"
+  fi
+}
+
 geoip_metadb() {
-  FILE_P="$TARGET_DIR""GeoIP.metadb"
-  wget --continue "$GeoIP_metadb" -O "$FILE_P"
+  TARGET_NAME="GeoIP.metadb"
+  SRC_NAME="geoip.metadb"
+  dd "$TARGET_NAME" "$SRC_NAME"
 }
 
 geoip_dat() {
-  FILE_P="$TARGET_DIR""GeoIP.dat"
-  wget --continue "$GeoIP_dat" -O "$FILE_P"
+  TARGET_NAME="GeoIP.dat"
+  SRC_NAME="geoip.dat"
+  dd "$TARGET_NAME" "$SRC_NAME"
 }
 
 geosite_dat() {
-  FILE_P="$TARGET_DIR""GeoSite.dat"
-  wget --continue "$GeoSite_dat" -O "$FILE_P"
+  TARGET_NAME="GeoSite.dat"
+  SRC_NAME="geosite.dat"
+  dd "$TARGET_NAME" "$SRC_NAME"
 }
 
 clear_all() {
